#!/usr/bin/env python
"""
launches an instance of spazzer
"""
import os
import spazzer
ETC_DIR = os.path.join(os.path.dirname(spazzer.__file__),"etc")

import sys
from paste.deploy import loadapp
from paste import httpserver as server
app = loadapp("config:%s/config.ini" % ETC_DIR)

server.serve(app,port=8088)

