#!/usr/bin/env python
"""
launches an instance of spazzer
"""
import os
import spazzer
import sys
from paste.deploy import loadapp
from paste import httpserver as server

ETC_DIR = os.path.join(os.path.dirname(spazzer.__file__), "etc")
app = loadapp("config:%s/config.ini" % ETC_DIR)
server.serve(app,host = 0.0.0.0, port = 8088)
